### PR TITLE
STYLE: Add ITK prefix to testing macros

### PR DESCRIPTION
**Pull request by jhlegarreta**

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex @dzenanz @hjmjohnson reviews are welcome. Thanks.

**Comment by thewtex** [comment]
Thanks @jhlegarreta !

Rebasing...

**Comment by thewtex** [comment]
@jhlegarreta I did not have permissions to push to your topic. Could it please be updated?

**Comment by thewtex** [comment]
@jhlegarreta sorry, typo in the branch name -- fixed :upside_down_face:

**Comment by jhlegarreta** [comment]
:+1:  Thanks @thewtex !

**Pull request merged**
